name: analysis3
channels:
- conda-forge
- coecms
- scitools
dependencies:
- python=3
- basemap
- cartopy
- dask=0.15.1
- distributed=1.18.0
- ipython
- iris
- netCDF4
- numpy
- pandas=0.20.3
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- pybufr-ecmwf
- jupyter
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh=0.12.4
- datashader
- f90nml
- wrf-python
- sympy
- sh
- basemap-data-hires
- dataset
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- gdal
- umtools
- compliance-checker
- arccssive
- poppler<0.61 # Pinned for GDAL prereq
- xerces-c<3.2 # Pinned for GDAL prereq
- ncimonitor
