name: analysis3
channels:
- conda-forge
- coecms
- scitools
dependencies:
- python=3
- basemap
- cartopy
- dask
- ipython
- iris
- netCDF4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- pybufr-ecmwf
- jupyter
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
- basemap-data-hires
- dataset
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- gdal
